# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7505fba90536ad41ab91e7115de77e802e1c21e7503e4a099488540fcebf928a9ad7ed585119be357009f89931baea0a3cd8dd79ae86854c7d3360c29a9d4070

test:
  secret_key_base: 9b6e4bf3eecc83196feb6f8e61dcbf3a73e3d503a8dd4b4ccfad6540523bd9e6b1daaf82566a2ec04327135cd521c29c99b98c78b7f37558973d2c4d6f4a4653

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
